name: CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.4.1
      with:
        virtualenvs-create: false
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint
      run: |
        make lint
    - name: Integration Tests
      run: |
        make integration_test
